import psycopg2
connect_dict = {'dbname': 'fosztas', 'user':'postgres', 'password': 'zsakaszi666', 'host': 'localhost'}
create_profile=''' CREATE TABLE IF NOT EXISTS tennis.profile (
                    Name varchar(50) Primary Key, 
                    Age varchar(50), 
                    Country varchar(50),
                    Birthplace varchar(50), 
                    Residence varchar(50),
                    Height varchar(50), 
                    Weight varchar(50),
                    Plays varchar(50), 
                    Backhand varchar(50), 
                    Favorite_Surface varchar(50), 
                    Coach varchar(50), 
                    Turned_Pro INT,
                    Seasons varchar(50), 
                    Active varchar(50), 
                    Prize_Money varchar(50), 
                    Wikipedia varchar(50), 
                    Website varchar(50), 
                    Facebook varchar(50),
                    Twitter varchar(50), 
                    Nicknames varchar(50), 
                    Titles varchar(50), 
                    Grand_Slams varchar(50), 
                    Tour_Finals varchar(50),
                    Masters varchar(50), 
                    Davis_Cups varchar(50), 
                    Team_Cups varchar(50), 
                    Current_Rank varchar(50), 
                    Best_Rank varchar(50),
                    Current_Elo_Rank varchar(50), 
                    Best_Elo_Rank varchar(50), 
                    Peak_Elo_Rating varchar(50), 
                    GOAT_Rank varchar(50),
                    Weeks_at_No_1 INT, 
                    Best_Season varchar(50), 
                    Last_Appearance varchar(50), 
                    Overall varchar(50), 
                    Hard varchar(50), 
                    Clay varchar(50), 
                    Grass varchar(50), 
                    Carpet varchar(50)
)'''

create_links = '''CREATE TABLE IF NOT EXISTS tennis.links (
                   link varchar (70) 
)'''
create_performance = '''CREATE TABLE IF NOT EXISTS tennis.performance(
                    Player varchar(50) Primary Key,
                    Hard varchar(50),
                    Clay varchar(50),
                    Grass varchar(50),
                    Carpet varchar(50),
                    Grand_Slam varchar(50),
                    Tour_Finals varchar(50),
                    Masters varchar(50),
                    Olympics varchar(50),
                    ATP_500 varchar(50),
                    ATP_250 varchar(50),
                    Davis_Cup varchar(50),
                    Team_Cups varchar(50),
                    Deciding_Set varchar(50),
                    Fifth_Set varchar(50),
                    After_Winning_1st_Set varchar(50),
                    After_Losing_1st_Set varchar(50),
                    Tie_Breaks varchar(50),
                    Deciding_Set_Tie_Breaks varchar(50),
                    Outdoor varchar(50),
                    Indoor varchar(50),
                    Best_of_3 varchar(50),
                    Best_of_5 varchar(50),
                    Vs_No_1 varchar(50),
                    Vs_Top_5 varchar(50),
                    Vs_Top_10 varchar(50),
                    Vs_Top_20 varchar(50),
                    Vs_Top_50 varchar(50),
                    Vs_Top_100 varchar(50),
                    Vs_100__Ranked varchar(50),
                    Vs_Higher_Ranked varchar(50),
                    Vs_Lower_Ranked varchar(50),
                    Final_round varchar(50),
                    For_Bronze_Medal_round varchar(50),
                    Semi_Final_round varchar(50),
                    Quarter_Final_round varchar(50),
                    Round_of_16_round varchar(50),
                    Round_of_32_round varchar(50),
                    Round_of_64_round varchar(50),
                    Round_of_128_round varchar(50),
                    Round_Robin_round varchar(50),
                    Very_Fast varchar(50),
                    Fast varchar(50),
                    Medium_Fast varchar(50),
                    Medium varchar(50),
                    Medium_Slow varchar(50),
                    Slow varchar(50),
                    Very_Slow varchar(50),
                    Vs_Higher_Elo varchar(50),
                    Vs_Lower_Elo varchar(50),
                    Vs_Right_Handed varchar(50),
                    Vs_Left_Handed varchar(50),
                    Vs_Two_Handed_bh varchar(50),
                    Vs_One_Handed_bh varchar(50),
                    Vs_Younger varchar(50),
                    Vs_Older varchar(50),
                    Vs_Shorter varchar(50),
                    Vs_Taller varchar(50),
                    Title_result varchar(50),
                    Final_result varchar(50),
                    Semi_Final_result varchar(50),
                    Quarter_Final_result varchar(50),
                    Round_of_16_result varchar(50),
                    Round_of_32_result varchar(50),
                    Round_of_64_result varchar(50),
                    Round_of_128_result varchar(50),
                    Round_Robin_result varchar(50),
                    Bronze_Medal_result varchar(50),
                    Best_of_3__2_0  varchar(50),
                    Best_of_3__2_1  varchar(50),
                    Best_of_3__1_2  varchar(50),
                    Best_of_3__0_2  varchar(50),
                    Best_of_5__3_0  varchar(50),
                    Best_of_5__3_1  varchar(50),
                    Best_of_5__3_2  varchar(50),
                    Best_of_5__2_3  varchar(50),
                    Best_of_5__1_3  varchar(50),
                    Best_of_5__0_3  varchar(50)
)'''

create_statistics='''CREATE TABLE IF NOT EXISTS tennis.statistics(
                    Aces varchar(50),
                    Ace_pct varchar(50),
                    Aces_per_Svc_Game varchar(50),
                    Aces_per_Set varchar(50),
                    Aces_per_Match varchar(50),
                    Double_Faults varchar(50),
                    Double_Fault_pct varchar(50),
                    DFs_per_Second_Serve_pct varchar(50),
                    DFs_per_Svc_Game varchar(50),
                    DFs_per_Set varchar(50),
                    DFs_per_Match varchar(50),
                    Aces_per_DFs_Ratio varchar(50),
                    Ace_Against varchar(50),
                    Ace_Against_pct varchar(50),
                    Double_Faults_Against varchar(50),
                    Double_Fault_Against_pct varchar(50),
                    First_Serve_pct varchar(50),
                    First_Serve_Won_pct varchar(50),
                    Second_Serve_Won_pct varchar(50),
                    First_Serve_Effectiveness varchar(50),
                    Serve_Rating varchar(50),
                    Service_Points_Won_pct varchar(50),
                    Svc_In_play_Pts_Won_pct varchar(50),
                    Points_per_Service_Game varchar(50),
                    Pts_Lost_per_Svc_Game varchar(50),
                    Break_Points_Saved_pct varchar(50),
                    BPs_per_Svc_Game varchar(50),
                    BPs_Faced_per_Set varchar(50),
                    BPs_Faced_per_Match varchar(50),
                    Service_Games_Won_pct varchar(50),
                    Svc_Gms_Lost_per_Set varchar(50),
                    Svc_Gms_Lost_per_Match varchar(50),
                    Serve_Max_Speed varchar(50),
                    First_Serve_Average_Speed varchar(50),
                    Second_Serve_Average_Speed varchar(50),
                    Serve_Average_Speed varchar(50),
                    First_per_Second_Srv_Spd_Ratio varchar(50),
                    Srv_Max_per_Avg_Spd_Ratio varchar(50),
                    First_Srv_Return_Won_pct varchar(50),
                    Second_Srv_Return_Won_pct varchar(50),
                    Return_Rating varchar(50),
                    Return_Points_Won_pct varchar(50),
                    Rtn_In_play_Pts_Won_pct varchar(50),
                    Points_per_Return_Game varchar(50),
                    Pts_Won_per_Rtn_Game varchar(50),
                    Break_Points_Won_pct varchar(50),
                    BPs_per_Return_Game varchar(50),
                    BPs_per_Set varchar(50),
                    BPs_per_Match varchar(50),
                    Return_Games_Won_pct varchar(50),
                    Rtn_Gms_Won_per_Set varchar(50),
                    Rtn_Gms_Won_per_Match varchar(50),
                    Total_Points_Played varchar(50),
                    Total_Points_Won varchar(50),
                    Total_Points_Won_pct varchar(50),
                    Tot_Second_Srv_In_pl_Pts_W_pct varchar(50),
                    Total_Break_Points_Won_pct varchar(50),
                    Rtn_to_Svc_Points_Ratio varchar(50),
                    Points_per_Game varchar(50),
                    Points_per_Set varchar(50),
                    Points_per_Match varchar(50),
                    Winner_pct varchar(50),
                    Unforced_Error_pct varchar(50),
                    Forced_Error_pct varchar(50),
                    Winners_per_UEs_Ratio varchar(50),
                    Winner_Against_pct varchar(50),
                    UE_Against_pct varchar(50),
                    FE_Against_pct varchar(50),
                    Wnrs_per_FEs_Against_Ratio varchar(50),
                    Net_Points_pct varchar(50),
                    Net_Points_Won_pct varchar(50),
                    Points_Won_at_Net_pct varchar(50),
                    Net_Effectiveness varchar(50),
                    Total_Games_Played varchar(50),
                    Total_Games_Won varchar(50),
                    Games_Won_pct varchar(50),
                    Games_per_Set varchar(50),
                    Games_per_Match varchar(50),
                    Tie_Breaks_Played varchar(50),
                    Tie_Breaks_Won varchar(50),
                    Tie_Breaks_Won_pct varchar(50),
                    Tie_Breaks_per_Set_pct varchar(50),
                    Tie_Breaks_per_Match varchar(50),
                    Sets_Played varchar(50),
                    Sets_Won varchar(50),
                    Sets_Won_pct varchar(50),
                    Sets_per_Match varchar(50),
                    Matches_Played varchar(50),
                    Matches_Won varchar(50),
                    Matches_Won_pct varchar(50),
                    Points_Dominance varchar(50),
                    In_play_Points_Dominance varchar(50),
                    Second_Srv_In_play_Pts_Dom varchar(50),
                    Games_Dominance varchar(50),
                    Break_Points_Ratio varchar(50),
                    Pts_to_Matches_Over_Perf varchar(50),
                    Pts_to_Sets_Over_Perf varchar(50),
                    Pts_to_Gms_Over_Perf varchar(50),
                    S_Pts_to_S_Gms_Ov_Perf varchar(50),
                    R_Pts_to_R_Gms_Ov_Perf varchar(50),
                    Pts_to_TBs_Over_Perf varchar(50),
                    Gms_to_Matches_Ov_Perf varchar(50),
                    Gms_to_Sets_Over_Perf varchar(50),
                    Sets_to_Matches_Ov_Perf varchar(50),
                    BPs_Over_Performing varchar(50),
                    BPs_Saved_Over_Perf varchar(50),
                    BPs_Conv_Over_Perf varchar(50),
                    Opponent_Rank varchar(50),
                    Opponent_Elo_Rating varchar(50),
                    Upsets_scored varchar(50),
                    Upsets_scored_pct varchar(50),
                    Upsets_against varchar(50),
                    Upsets_against_pct varchar(50),
                    Upsets varchar(50),
                    Upsets_pct varchar(50),
                    Point_Time_seconds varchar(50),
                    Game_Time_minutes varchar(50),
                    Set_Time_minutes varchar(50),
                    Match_Time varchar(50),
                    player varchar(50) Primary Key)'''

create_matches = '''CREATE TABLE IF NOT EXISTS tennis.matches(
                    Date varchar(50),
                    Tournament varchar(50),
                    Surface varchar(50),
                    Round varchar(50),
                    Score varchar(50),
                    Winner varchar(50),
                    Loser varchar(50),
                    Winner_elo varchar(50),
                    Winner_rank varchar(50),
                    Loser_elo varchar(50),
                    Loser_rank varchar(50))
'''

update_links = '''UPDATE tennis.links

'''










#GET column names instead of hard coding it.
"""
conn = psycopg2.connect(**connect_dict)
cursor = conn.cursor()
statement = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'profile'"
cursor.execute(statement)
print(cursor.fetchall())
conn.commit()
cursor.close()
conn.close()"""